declare module '*.jpg'
declare module '*.png'
declare module '*.jpeg'
declare module '*.gif'
declare module '*.ico'
declare module '*.svg'

declare module 'remark-breaks'
declare module 'rehype-stringify'
declare module 'remark-rehype'
